apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j5lq08v7g-java-springboot 
  janus-idp.io/tekton: j5lq08v7g-java-springboot
  backstage.io/kubernetes-id: j5lq08v7g-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5lq08v7g-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  